package model;
// Generated 07.Aðu.2019 23:00:39 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products", catalog = "product_tracker")
public class Products implements java.io.Serializable {

	private Integer pid;
	private String pname;
	private String pbrand;
	private String pmadein;
	private int pprice;

	public Products() {
	}

	public Products(String pname, String pbrand, String pmadein, int pprice) {
		this.pname = pname;
		this.pbrand = pbrand;
		this.pmadein = pmadein;
		this.pprice = pprice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pid", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "pname", nullable = false)
	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	@Column(name = "pbrand", nullable = false)
	public String getPbrand() {
		return this.pbrand;
	}

	public void setPbrand(String pbrand) {
		this.pbrand = pbrand;
	}

	@Column(name = "pmadein", nullable = false)
	public String getPmadein() {
		return this.pmadein;
	}

	public void setPmadein(String pmadein) {
		this.pmadein = pmadein;
	}

	@Column(name = "pprice", nullable = false)
	public int getPprice() {
		return this.pprice;
	}

	public void setPprice(int pprice) {
		this.pprice = pprice;
	}

}
