package model;
// Generated 05.Aðu.2019 12:00:38 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", catalog = "proje_ee")
public class Cart implements java.io.Serializable {

	private Integer crid;
	private String cmail;
	private String cpassword;
	private String cname;
	private String csurname;
	private String cphone;
	private int cid;
	private String cnote;

	public Cart() {
	}

	public Cart(String cmail, String cpassword, String cname, String csurname, String cphone, int cid, String cnote) {
		this.cmail = cmail;
		this.cpassword = cpassword;
		this.cname = cname;
		this.csurname = csurname;
		this.cphone = cphone;
		this.cid = cid;
		this.cnote = cnote;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "crid", unique = true, nullable = false)
	public Integer getCrid() {
		return this.crid;
	}

	public void setCrid(Integer crid) {
		this.crid = crid;
	}

	@Column(name = "cmail", nullable = false)
	public String getCmail() {
		return this.cmail;
	}

	public void setCmail(String cmail) {
		this.cmail = cmail;
	}

	@Column(name = "cpassword", nullable = false)
	public String getCpassword() {
		return this.cpassword;
	}

	public void setCpassword(String cpassword) {
		this.cpassword = cpassword;
	}

	@Column(name = "cname", nullable = false)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@Column(name = "csurname", nullable = false)
	public String getCsurname() {
		return this.csurname;
	}

	public void setCsurname(String csurname) {
		this.csurname = csurname;
	}

	@Column(name = "cphone", nullable = false, length = 12)
	public String getCphone() {
		return this.cphone;
	}

	public void setCphone(String cphone) {
		this.cphone = cphone;
	}

	@Column(name = "cid", nullable = false)
	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	@Column(name = "cnote", nullable = false)
	public String getCnote() {
		return this.cnote;
	}

	public void setCnote(String cnote) {
		this.cnote = cnote;
	}

}
