package model;
// Generated 05.Aðu.2019 12:00:38 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "categories", catalog = "proje_ee")
public class Categories implements java.io.Serializable {

	private CategoriesId id;

	public Categories() {
	}

	public Categories(CategoriesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "cid", column = @Column(name = "cid", nullable = false)),
			@AttributeOverride(name = "ctitle", column = @Column(name = "ctitle", nullable = false)) })
	public CategoriesId getId() {
		return this.id;
	}

	public void setId(CategoriesId id) {
		this.id = id;
	}

}
