package model;
// Generated 05.Aðu.2019 12:00:38 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategoriesId generated by hbm2java
 */
@Embeddable
public class CategoriesId implements java.io.Serializable {

	private int cid;
	private String ctitle;

	public CategoriesId() {
	}

	public CategoriesId(int cid, String ctitle) {
		this.cid = cid;
		this.ctitle = ctitle;
	}

	@Column(name = "cid", nullable = false)
	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	@Column(name = "ctitle", nullable = false)
	public String getCtitle() {
		return this.ctitle;
	}

	public void setCtitle(String ctitle) {
		this.ctitle = ctitle;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategoriesId))
			return false;
		CategoriesId castOther = (CategoriesId) other;

		return (this.getCid() == castOther.getCid())
				&& ((this.getCtitle() == castOther.getCtitle()) || (this.getCtitle() != null
						&& castOther.getCtitle() != null && this.getCtitle().equals(castOther.getCtitle())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCid();
		result = 37 * result + (getCtitle() == null ? 0 : this.getCtitle().hashCode());
		return result;
	}

}
