package model;
// Generated 05.Aðu.2019 12:00:38 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "proje_ee")
public class Users implements java.io.Serializable {

	private Integer uid;
	private String uname;
	private String usurname;
	private String umail;
	private String upassword;
	private String uimg;
	private int uprice;

	public Users() {
	}

	public Users(String uname, String usurname, String umail, String upassword, String uimg, int uprice) {
		this.uname = uname;
		this.usurname = usurname;
		this.umail = umail;
		this.upassword = upassword;
		this.uimg = uimg;
		this.uprice = uprice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "uid", unique = true, nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "uname", nullable = false)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "usurname", nullable = false)
	public String getUsurname() {
		return this.usurname;
	}

	public void setUsurname(String usurname) {
		this.usurname = usurname;
	}

	@Column(name = "umail", nullable = false)
	public String getUmail() {
		return this.umail;
	}

	public void setUmail(String umail) {
		this.umail = umail;
	}

	@Column(name = "upassword", nullable = false)
	public String getUpassword() {
		return this.upassword;
	}

	public void setUpassword(String upassword) {
		this.upassword = upassword;
	}

	@Column(name = "uimg", nullable = false)
	public String getUimg() {
		return this.uimg;
	}

	public void setUimg(String uimg) {
		this.uimg = uimg;
	}

	@Column(name = "uprice", nullable = false)
	public int getUprice() {
		return this.uprice;
	}

	public void setUprice(int uprice) {
		this.uprice = uprice;
	}

}
